# Generated by Django 4.2.20 on 2025-03-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favourites_subgenre',
            new_name='favourite_subgenres',
        ),
    ]
