# Generated by Django 4.2.20 on 2025-03-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_alter_followband_following_band'),
        ('users', '0004_rename_favourites_subgenre_profile_favourite_subgenres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourite_subgenres',
            field=models.ManyToManyField(blank=True, max_length=50, to='reviews.subgenre', verbose_name='Любимые поджанры'),
        ),
    ]
