# Generated by Django 4.2.20 on 2025-03-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_band_alter_comment_author_alter_comment_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(null=True, verbose_name='Оценка'),
        ),
    ]
