# Generated by Django 4.2.20 on 2025-03-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='description',
        ),
        migrations.AddField(
            model_name='title',
            name='text',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Текст песни'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Год выпуска'),
        ),
    ]
