# Generated by Django 4.2.20 on 2025-03-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_title_description_title_text_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='subgenre',
            field=models.ManyToManyField(blank=True, null=True, related_name='subgenre_title', to='reviews.subgenre', verbose_name='Поджанр'),
        ),
    ]
