# Generated by Django 4.2.20 on 2025-03-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_title_subgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='subgenre',
            field=models.ManyToManyField(related_name='subgenre_title', to='reviews.subgenre', verbose_name='Поджанр'),
        ),
    ]
