# Generated by Django 4.2.20 on 2025-03-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_title_subgenre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgenre',
            name='name',
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(db_index=True, max_length=70, unique=True, verbose_name='Музыкальная группа'),
        ),
        migrations.AlterField(
            model_name='subgenre',
            name='slug',
            field=models.SlugField(max_length=40, unique=True, verbose_name='Уникальное имя поджанра'),
        ),
    ]
