# Generated by Django 4.2.20 on 2025-03-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_subgenre_name_alter_band_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgenre',
            old_name='slug',
            new_name='name',
        ),
    ]
