# Generated by Django 4.2.20 on 2025-03-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_rename_slug_subgenre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Описание музыкальной группы'),
        ),
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rockrew/images/', verbose_name='Фото группы'),
        ),
        migrations.AlterField(
            model_name='subgenre',
            name='name',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Уникальное имя поджанра'),
        ),
    ]
