# Generated by Django 4.2.20 on 2025-03-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_band_description_band_image_alter_subgenre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rockrev/images/', verbose_name='Фото группы'),
        ),
    ]
