# Generated by Django 4.2.20 on 2025-03-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_band_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'verbose_name': 'Муз.Группа', 'verbose_name_plural': 'Муз.Группы'},
        ),
        migrations.AddField(
            model_name='subgenre',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг группы'),
        ),
        migrations.AlterField(
            model_name='band',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг группы'),
        ),
    ]
