# Generated by Django 4.2.20 on 2025-03-24 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0015_alter_band_options_subgenre_slug_alter_band_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_band', to='reviews.band', verbose_name='Избранная группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='followband',
            constraint=models.UniqueConstraint(fields=('user', 'following_band'), name='unique_follow'),
        ),
    ]
