# Generated by Django 4.2.20 on 2025-03-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_followband_followband_unique_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followband',
            name='following_band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_follows', to='reviews.band', verbose_name='Избранная группа'),
        ),
    ]
