# Generated by Django 4.2.20 on 2025-03-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_alter_followband_following_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='band',
            field=models.ManyToManyField(blank=True, null=True, related_name='band_title', to='reviews.band', verbose_name='Музыкальная группа'),
        ),
        migrations.AlterField(
            model_name='title',
            name='subgenre',
            field=models.ManyToManyField(blank=True, null=True, related_name='subgenre_title', to='reviews.subgenre', verbose_name='Поджанр'),
        ),
    ]
