# Generated by Django 4.2.20 on 2025-03-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_alter_title_band_alter_title_subgenre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='band',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание группы'),
        ),
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='band/images/', verbose_name='Изображение группы'),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(db_index=True, max_length=70, verbose_name='Музыкальная группа'),
        ),
        migrations.AlterField(
            model_name='subgenre',
            name='name',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Уникальное имя поджанра'),
        ),
        migrations.AlterUniqueTogether(
            name='band',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='subgenre',
            unique_together={('name',)},
        ),
    ]
