# Generated by Django 4.2.20 on 2025-03-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_alter_band_options_alter_band_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='band',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subgenre',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='band',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_band_name'),
        ),
        migrations.AddConstraint(
            model_name='subgenre',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_subgenre_name'),
        ),
    ]
