# Generated by Django 4.2.20 on 2025-03-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_alter_band_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='band',
            name='unique_band_name',
        ),
        migrations.RemoveConstraint(
            model_name='subgenre',
            name='unique_subgenre_name',
        ),
    ]
